/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum MergeStrategy {
  Or = 0,
  And = 1,
  AndNot = 2
}
export const enum DeduplicateStrategy {
  KeepAll = 0,
  KeepFirst = 1,
  RemoveSimilar = 2,
  Reduce = 3,
  CrossJoin = 4,
  CrossJoinAndRemoveSimilar = 5
}
export interface MergeOptions {
  output: string
  mergeStrategy: MergeStrategy
  deduplicateStrategy: DeduplicateStrategy
  leftKey: string
  rightKey: string
  isNumberKey?: boolean
}
export function merge(leftPath: string, rightPath: string, options: MergeOptions): Promise<void>
